{{- if .Values.config.textSearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idv.fullname" . }}-indexer
  labels:
    {{- include "idv.indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.indexer.replicas }}
  selector:
    matchLabels:
      {{- include "idv.indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configs/idv-config.yaml") . | sha256sum }}
        checksum/version: {{ .Values.versionSha | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "idv.indexer.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "idv.serviceAccountName" . }}
      {{- with .Values.indexer.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.licenseSecretName }}
      - name: license
        secret:
          secretName: {{ .Values.licenseSecretName }}
      {{- end }}
      - name: idv-config
        configMap:
          name: {{ include "idv.fullname" . }}-config
          items:
            - key: idv-config
              path: idv-config.yaml
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: indexer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.indexer.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        {{- if .Values.licenseSecretName }}
        - name: license
          mountPath: /app/extBin/unix/regula.license
          subPath: regula.license
          readOnly: true
        {{- end }}
        - name: idv-config
          mountPath: /app/config.yaml
          subPath: idv-config.yaml
        command: ["idv"]
        args: ["indexer", "start"]
        env: {{- tpl (toYaml .Values.env) . | nindent 10 }}
{{- end }}
