{{- if .Values.ingress.enabled -}}
{{- $defaultServiceName := printf "%s-api" (include "idv.fullname" .) -}}
{{- $defaultServicePort := .Values.api.service.port -}}
{{- $paths := .Values.ingress.paths -}}
{{- $pathType := .Values.ingress.pathType | default "Prefix" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "idv.fullname" . }}
  labels: {{- include "idv.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
        {{- range $p := $paths }}
          {{- if kindIs "map" $p }}
          - path: {{ tpl $p.path $ }}
            pathType: {{ $p.pathType | default $pathType }}
            backend:
              service:
                {{- if $p.action }}
                name: {{ $p.action }}
                port:
                  name: use-annotation
                {{- else }}
                name: {{ $p.service.name | default $defaultServiceName }}
                port:
                  number: {{ $p.service.port | default $defaultServicePort }}
                {{- end }}
          {{- else }}
          - path: {{ tpl $p $ }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $defaultServiceName }}
                port:
                  number: {{ $defaultServicePort }}
          {{- end }}
        {{- end }}
    {{- end -}}
  {{- else }}
    - http:
        paths:
        {{- range $p := $paths }}
          {{- if kindIs "map" $p }}
          - path: {{ tpl $p.path $ }}
            pathType: {{ $p.pathType | default $pathType }}
            backend:
              service:
                {{- if $p.action }}
                name: {{ $p.action }}
                port:
                  name: use-annotation
                {{- else }}
                name: {{ $p.service.name | default $defaultServiceName }}
                port:
                  number: {{ $p.service.port | default $defaultServicePort }}
                {{- end }}
          {{- else }}
          - path: {{ tpl $p $ }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $defaultServiceName }}
                port:
                  number: {{ $defaultServicePort }}
          {{- end }}
        {{- end }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
