{{- if or .Values.workflow.podDisruptionBudget.enabled .Values.workflow.autoscaling.enabled }}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: {{ include "idv.fullname" . }}-workflow
  labels:
    {{- include "idv.workflow.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "idv.workflow.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.workflow.podDisruptionBudget.config | nindent 2 }}
{{- end }}
