{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "idv.fullname" . }}
  labels:
    {{- include "idv.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  {{- if .Values.rbac.useExistingRole }}
  name: {{ .Values.rbac.useExistingRole }}
  {{- else }}
  name: {{ include "idv.fullname" . }}
  {{- end }}
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceAccount.create }}
  name: {{ include "idv.serviceAccountName" . }}
  {{- else }}
  name: default
  {{- end }}
{{- end }}
