{{- if and .Values.rbac.create (not .Values.rbac.useExistingRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "idv.fullname" . }}
  labels:
    {{- include "idv.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.rbac.extraRoleRules }}
rules:
  {{- with .Values.rbac.extraRoleRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- else }}
rules: []
{{- end }}
{{- end }}
