# apiVersion v2 is Helm 3
---
apiVersion: v2
name: docreader
home: https://api.regulaforensics.com/
version: 2.7.0
appVersion: 9.2.317908.2109
description: Fast and accurate data extraction from identity documents. On-premise and cloud integration
icon: https://secure.gravatar.com/avatar/71a5efd69d82e444129ad18f51224bbb.jpg
keywords:
  - regula
  - docreader
  - regulaforensics
dependencies:
  - name: postgresql
    version: 13.4.4
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
maintainers:
  - email: support@regulaforensics.com
    name: Regula Forensics Support
    url: https://support.regulaforensics.com
type: application
