---
{{- if and (not .Values.logs.persistence.existingClaim ) .Values.logs.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "logs_volume_claim" . }}
  labels:
    tier: docreader
    component: logs-pvc
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.logs.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.logs.persistence.size | quote }}
  {{- if .Values.logs.persistence.storageClassName }}
  {{- if (eq "-" .Values.logs.persistence.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.logs.persistence.storageClassName }}"
  {{- end }}
  {{- end }}
{{- end }}