{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "faceapi.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $pathType := .Values.ingress.pathType | default "Prefix" -}}
{{- $globalPaths := .Values.ingress.paths | default (list "/") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "faceapi.fullname" . }}
  labels: {{- include "faceapi.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- if and (gt (len .Values.ingress.hosts) 0) (typeIs "map[string]interface {}" (index .Values.ingress.hosts 0)) (hasKey (index .Values.ingress.hosts 0) "host") }}
      {{- range $hostConfig := .Values.ingress.hosts }}
      {{- $host := $hostConfig.host }}
      {{- $paths := $hostConfig.paths | default $globalPaths }}
    - host: {{ tpl $host $ }}
      http:
        paths:
        {{- range $p := $paths }}
          {{- if kindIs "map" $p }}
          - path: {{ tpl $p.path $ }}
            pathType: {{ $p.pathType | default $pathType }}
            backend:
              service:
                {{- if $p.action }}
                name: {{ $p.action }}
                port:
                  name: use-annotation
                {{- else }}
                name: {{ $p.service.name | default $serviceName }}
                port:
                  number: {{ $p.service.port | default $servicePort }}
                {{- end }}
          {{- else }}
          - path: {{ tpl $p $ }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
        {{- end -}}
      {{- end -}}
    {{- else }}
      {{- range $host := .Values.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
        {{- range $p := $globalPaths }}
          {{- if kindIs "map" $p }}
          - path: {{ tpl $p.path $ }}
            pathType: {{ $p.pathType | default $pathType }}
            backend:
              service:
                {{- if $p.action }}
                name: {{ $p.action }}
                port:
                  name: use-annotation
                {{- else }}
                name: {{ $p.service.name | default $serviceName }}
                port:
                  number: {{ $p.service.port | default $servicePort }}
                {{- end }}
          {{- else }}
          - path: {{ tpl $p $ }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- else }}
    - http:
        paths:
        {{- range $p := $globalPaths }}
          {{- if kindIs "map" $p }}
          - path: {{ tpl $p.path $ }}
            pathType: {{ $p.pathType | default $pathType }}
            backend:
              service:
                {{- if $p.action }}
                name: {{ $p.action }}
                port:
                  name: use-annotation
                {{- else }}
                name: {{ $p.service.name | default $serviceName }}
                port:
                  number: {{ $p.service.port | default $servicePort }}
                {{- end }}
          {{- else }}
          - path: {{ tpl $p $ }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
        {{- end -}}
  {{- end -}}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
